# Generated by Django 4.2.8 on 2023-12-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='cover',
        ),
        migrations.AddField(
            model_name='music',
            name='length',
            field=models.FloatField(default=0.0, verbose_name='分数'),
        ),
        migrations.AddField(
            model_name='music',
            name='order',
            field=models.IntegerField(default=0, verbose_name='滑走順'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music',
            field=models.FileField(upload_to='music/files/', verbose_name='ファイル名'),
        ),
        migrations.AlterField(
            model_name='music',
            name='skater',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=50, verbose_name='曲名'),
        ),
    ]
